services:
  db:
    container_name: app_db
    # restart: always
    image: postgres:latest
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5431:5432"
    env_file:
      - ./secrets/db/.env

  # frontend:

  app_service_0:
    container_name: app_service_0
    depends_on:
      - db
    stdin_open: true
    tty: true
    ports:
      - "8200:8200"
    build:
      context: ./src/backend/app_service_0
      dockerfile: Dockerfile.dev
      args:
        HTTP_PORT: 8200
    develop:
      watch:
        - action: sync
          path: ./src/backend/app_service_0
          target: /app/src/backend/
        # - action: rebuild
        #   path: ./src/backend/go.mod
    env_file:
      - ./secrets/backend/.env_service_0

  app_service_1:
    container_name: app_service_1
    depends_on:
      - db
    stdin_open: true
    tty: true
    ports:
      - "8201:8200"
    build:
      context: ./src/backend/app_service_1
      dockerfile: Dockerfile.dev
      args:
        HTTP_PORT: 8200
    develop:
      watch:
        - action: sync
          path: ./src/backend/app_service_1
          target: /app/src/backend/
    env_file:
      - ./secrets/backend/.env_service_1

  mail:
    container_name: app_mail
    image: mailhog/mailhog:latest
    # restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

  redis:
    container_name: app_redis
    image: redis:latest
    # restart: always
    ports:
      - "6379:6379"
